Add basic components
ebeagusamuel/Bookstore-Redux- pull request #2
Opened 2020-10-30 15:58 UTC by cristianCeamatu

Created the basic containers and components for the Bookstore. 
Created and connected the store to the components.

2020-10-30 17:30 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi team :hand: 
Awesome job on this milestone so far :clap: :+1: 
We only need to make some small changes before moving on :smile: 

- [ ] Check my comments below.

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-10-30 17:30 UTC, Torres-ssf commented on src/components/Books.js
> +  const bookItems = books.map(book => <Book key={book.id} book={book} />);
- [ ] For this project we need to strictly follow the given provided instructions. We are not going to need the `Books` component. BookList will be in charge to map all books and create a Book component for each book.
![Screenshot from 2020-10-30 14-18-35](https://user-images.githubusercontent.com/30977845/97736678-d2ee3d80-1aba-11eb-8193-31d45a491248.png)

2020-10-30 17:30 UTC, Torres-ssf commented on src/components/AddBookForm.js
> +
- [ ] As it said in the requirements we are going to use only one component for the form: BookForm. It will be in charge to represent the form and also to control it. For this milestone, the `handlesubmit` functionality does not need to work, we are going to do that on the next one.
![Screenshot from 2020-10-30 14-14-23](https://user-images.githubusercontent.com/30977845/97736421-696e2f00-1aba-11eb-808e-286c2b4cec4b.png)

2020-10-30 17:30 UTC, Torres-ssf commented on src/App.js
> +    <div className="my-4 d-flex flex-column align-items-center justify-content-center">
- [ ] Since the `App` component it's a presentational component, we can move it to the `src/component` directory.
You can read more about the Redux pattern to divide components into Presentational and Container components [here](https://redux.js.org/basics/usage-with-react#presentational-and-container-components).

2020-10-31 08:05 UTC, lucasmazo23 approved these changes
## Project approved 🚀
### Great job!
### Your project looks great!
### You can go ahead and merge this pull request!
### Happy coding! 💻
## Lucas Mazo

2020-10-31 08:37 UTC, merged